### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by as51340**
Bump neo4j test
Bump neo4j-harness
Upgrade Clojure runtime.

Any feedback @chrisbetz ?

### CODE REVIEW

**Comment by as51340** [comment]
Hi @chrisbetz!
Yes I am using it with Memgraph.
Memgraph is an in-mem db using bolt protocol so it is basically the same.
Currently, the only thing I need is newer version of Java driver for Neo4j in order to support bolt+routing but I don't mind in becoming this connector.

**Comment by as51340** [comment]
@chrisbetz I see PR got merged, that's awesome, thanks! Can we hope for some soon release and deploy?

**Comment by chrisbetz** [comment]
Hi,

yes, I'm on it, but I switched hardware and need to re-setup infrastructure ... So, give me some moments for that, please.

**Comment by chrisbetz** [comment]
Ha, there you are: [4.2.0](https://clojars.org/gorillalabs/neo4j-clj/versions/4.2.0) it is.

**Comment by as51340** [comment]
Awesome thank you!

**Pull request merged**
